### ISSUE TITLE
Action URL to test if an item exists in a list

### ISSUE THREAD

**Issue by martinspain** [michaelrog/Shortlist#20]
I'm using Shortlist to provide a 'read later' list for users - they can add an entry to their 'read later' list from various places in the site where those entries are surfaced. I have a faceted search powered by SearchPlus and I'd like to integrate Shortlist with the results coming back from Algolia, so that users can add/remove items from their default list in the search results page too.

The search results are built dynamically via JavaScript using the JSON data sent back from Algolia so there's no way of knowing whether an item in the search results exists in the user's 'read later' list. There's no Twig involved in building the results so I can't use the standard Shortlist template tags to test if an Entry is already in the user's list.

In this case, it'd be really useful to have an action URL to query if an item exists in a list, so that when I'm building out the results in JS I ensure that I don't show an 'add' button for an Entry that already exists in the user's read later list and vice versa.

Unless I'm mistaken, that's not possible with the current set of actions documented [here](https://transition.topshelfcraft.com/software/craft/shortlist/usage/actions). I did have a quick look at the `craft_shortlist_item` database table to see if that could help, but that appears to persist items even after they've been removed from a list which is very confusing! If that is indeed the case, then I'm not sure where to look for a canonical reference of which items exist in which list.

Any help or advice would be gratefully received!

**Comment by michaelrog** [comment]
Thanks for the Feature Request, Martin!

I'm planning on shipping a full REST API with the Craft 3 version, which would make something like this very easy.

I don't have plans to add it into the Craft 2 branch, but I'd be open to PRs or a commission for custom dev to get it done. (support@topshelfcraft.com)

**Comment by martinspain** [comment]
That's great news for the C3 version! 

I actually ended up with a workaround for my particular use case by writing out a JavaScript array into the page template with the item IDs from the user's list in it, and then using those values in my render method that outputs the results from Algolia. This seems to work well, even if it's not quite as elegant a solution as I'd like!

**Comment by michaelrog** [comment]
Actually that's a perfectly elegant solution, which I have used before, both for faceting Algolia results _before_ a search, _and_ doing logic on those results _after_ the search. 👍👍
